targets:
  $default:
    builders:
      crystallis:
        generate_for:
          include:
            - lib/**.dart

builders:
  crystallis:
    import: "package:crystallis/codegen/generator.dart"
    builder_factories: ["crystallisBuilder"]
    build_extensions: {".dart": [".data.g.dart"]}
    auto_apply: dependents
    build_to: source