name: crystallis_example
description: Example for crystallis
version: 0.0.5-dev

publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  crystallis: any

dev_dependencies:
  crystallis_generator: any
  crystallis_plugin: any
  lints: ^6.0.0
  build_runner: ^2.13.1
