name: crystallis_example
description: Example for crystallis
version: 0.0.5-dev

publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  crystallis:
    path: ../../

dev_dependencies:
  crystallis_generator:
    path: ../../../crystallis_generator
  crystallis_plugin:
    path: ../../../crystallis_plugin
  lints: ^6.0.0
  build_runner: ^2.13.1
