include:
  - package:lints/recommended.yaml
  - ../../analysis_options.yaml #plugins

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    unused_import: warning
    dead_code: warning
    public_member_api_docs: error
    unnecessary_this: ignore

linter:
  rules:
    - public_member_api_docs
    - await_only_futures
    - discarded_futures
    - unawaited_futures
    - avoid_slow_async_io
    - avoid_void_async
    - unnecessary_async
    - unnecessary_string_escapes
    - unnecessary_raw_strings
    - prefer_single_quotes
    - avoid_escaping_inner_quotes

formatter:
  page_width: 120