name: crystallis_plugin
description: A plugin for the Crystallis code generator that provides additional verifications.
version: 0.0.5-dev
repository: https://github.com/kerberjg/crystallis.dart
license: MPL-2.0

environment:
  sdk: ">=3.10.0 <4.0.0"

resolution: workspace

dependencies:
  analysis_server_plugin: ^0.3.10
  analyzer: ^12.0.0
  analyzer_plugin: ^0.14.7
  collection: ^1.19.1
  crystallis_generator: ^0.0.5-dev
  meta: ^1.18.1
  path: ^1.9.0

dev_dependencies:
  analyzer_testing: ^0.2.1
  lints: ^6.0.0
  test: ^1.25.6
  test_reflective_loader: ^0.4.0
  crystallis: ^0.0.5-dev
  essential_lints_annotations: ^0.1.4
