name: "example"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop
      - "release/**"
    paths:
      - "packages/**/*.dart"
      - "packages/**/*.yaml"
      - "example/**/*.dart"
      - "example/**/*.yaml"
      - .github/workflows/example.yaml
  release:
    types: [published]

jobs:
  dart:
    strategy:
      matrix:
        include:
          - package: crystallis
            example: user
          - package: crystallis_generator
            example: copy_methods
    name: "${{ matrix.package }} (${{ matrix.example }})"
    uses: kerberjg/dart_flutter_ci_experiments/.github/workflows/pipeline.yaml@5499d308241da53d0b175b1a78e16056a97aa918
    with:
      path: "packages/${{ matrix.package }}/example/${{ matrix.example }}"
      force-sdk: dart
