name: "example"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop
      - "release/**"
    paths:
      - "packages/**/*.dart"
      - "packages/**/*.yaml"
      - "example/**/*.dart"
      - "example/**/*.yaml"
      - .github/workflows/example.yaml
  release:
    types: [published]

jobs:
  dart:
    name: "example"
    uses: kerberjg/dart_flutter_ci_experiments/.github/workflows/pipeline.yaml@4224e695167e35d90952e21953b2f933b0f045b0
    with:
      path: "packages/crystallis/example"
      force-sdk: dart
