name: "package"

on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - "release/**"
    paths:
      - "**.dart"
      - "./*.yaml"
      - .github/workflows/_base-dart.yaml
      - .github/workflows/package.yaml
  release:
    types: [published]

# call the base workflow with the package path
jobs:
  dart:
    uses: kerberjg/dart_flutter_ci_experiments/.github/workflows/pipeline.yaml@8ad47932f2fb94ccc84ae69f1057bf446454fb0e
    strategy:
      matrix:
        package:
          - crystallis
          - crystallis_generator
          - crystallis_plugin
    with:
      path: "packages/${{ matrix.package }}"
      force-sdk: dart
      min-publish-score: 150
